name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
  typecheck:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run typecheck || echo "No typecheck script yet"
  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run lint || echo "No lint script yet"
  unit:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run test:ci || echo "No test:ci script yet"
      - uses: actions/upload-artifact@v4
        with: { name: jest-report, path: jest*.html, if-no-files-found: ignore }
  build:
    needs: [typecheck, lint, unit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run build || echo "No build script yet"
  e2e:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npx playwright install --with-deps || true
      - run: npm run e2e || echo "No e2e script yet"
      - uses: actions/upload-artifact@v4
        with: { name: playwright-report, path: playwright-report, if-no-files-found: ignore }
  lighthouse:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npm run lighthouse || echo "No lighthouse script yet"
      - uses: actions/upload-artifact@v4
        with: { name: lighthouse, path: artifacts, if-no-files-found: ignore }
  sbom-scan:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'npm' }
      - run: npm ci
      - run: npx @cyclonedx/cyclonedx-npm --output-file sbom.json || true
      - run: npm audit --audit-level=high || true
      - uses: actions/upload-artifact@v4
        with: { name: sbom, path: sbom.json, if-no-files-found: ignore }
